### ISSUE TITLE
can't run gatsby develop

### ISSUE THREAD

**Issue by j2l** [BuilderIO/gatsby-starter-builder#22]
gatsby-cli is installed globally, and npm i is OK, but gatsby develop is crying:
![image](https://user-images.githubusercontent.com/65325/116778090-365c2680-aa70-11eb-9429-1d087cd6d0b3.png)
On Ubuntu 20.04; node v14.0.0, npm 7.10.0, Gatsby CLI version: 3.4.0

**Comment by teleaziz** [comment]
Hi @j2l , this sounds like an issue of a missing globally installed node modules, try using `npm run develop` instead or follow the steps here to fix your global node modules path:
https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found/15623632#15623632

**Comment by j2l** [comment]
Thank you @teleaziz 
Actually, when starting with a fresh new gatsby, then adding builder it worked.

**Comment by JOduMonT** [comment]
Personally when I install gatsby under ubuntu, I always have to do: `sudo npm install -g gatsby-cli`
then I `sudo chown -R :users /usr/lib/node_modules/` because my user is in that group.
