### ISSUE TITLE
ERROR #98124 WEBPACK ?? Content is missing ??

### ISSUE THREAD

**Issue by JOduMonT** [BuilderIO/gatsby-starter-builder#24]
Full disclaimer, I'm not a pro of Gatsby, this is why I want to use Builder.IO but I'm already stuck at integrating my [Public API Key](https://github.com/BuilderIO/gatsby-starter-builder#quick-start)

I Found it, this ok, but how to integrate it in `./src/config.js` is a mystery
here my line: `builderAPIKey: process.env.d4797e74-d1ba-406a-80f8-b750fb37e302`
but it give me an: ERROR #85923  GRAPHQL
for File: `src/layouts/PageLayout.jsx:20:5` which point at the content.

Technically I have 2 page published
![image](https://user-images.githubusercontent.com/5204724/117242214-d44e4900-ae02-11eb-9a15-a1daa7d635bc.png)

But when I visit https://wasp-commercial-green.builder.live/, Johnny don't think so
![image](https://user-images.githubusercontent.com/5204724/117242279-f34cdb00-ae02-11eb-9cab-9134408073ec.png)

### Here more detail on the error

> It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define
>  the schema for "Query":
> https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
> 
> File: src/templates/LandingPage.jsx:40:5
> 
> failed extract queries from components - 0.112s
> success write out requires - 0.004s
> 
>  ERROR #98124  WEBPACK
> 
> undefined failed
> 
> Can't resolve '../../public/page-data/sq/d/2865936176.json' in '/home/jond/website/my-builder-site/src/layouts'
> 
> If you're trying to use a package make sure that '../../public/page-data/sq/d/2865936176.json' is installed. If you're trying to use a local file make sure that the path is correct.
> 
> File: src/layouts/PageLayout.jsx

**Comment by JOduMonT** [comment]
I'll retry soon, now the page are showing under: https://wasp-commercial-green.builder.live/

**Comment by teleaziz** [comment]
@JOduMonT for the config change you just need to add your public api key to [src/config.js](https://github.com/BuilderIO/gatsby-starter-builder/blob/master/src/config.js#L4)
```
{
  builderAPIKey: "public-api-key"
}
```

For your page model domain on https://wasp-commercial-green.builder.live/, you're running into an issue where if you publish an empty page you get 404 Johnny in the response, this solved now and planned for release, to get around it please publish something in your page then bust the cache of the page (https://wasp-commercial-green.builder.live/?cachbust=true) , I'll keep this issue open until we release the fix.

**Comment by teleaziz** [comment]
An API released fixed the issue of 404 on empty content, let me know if the config change above didn't work for you.
